[project]
name = "iris-mcp-blueprint"
version = "0.1.1"
description = "Blueprint of an MCP server to work with InterSystems IRIS"
readme = "README.md"
authors = [
    { name = "Pietro Di Leo", email = "pietrodileo_00@yahoo.it" }
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "fastmcp>=3.2.4",
    "intersystems-irispython>=5.3.2",
    "requests>=2.33.1",
]

[project.urls]
Homepage = "https://github.com/pietrodileo/iris-mcp-blueprint"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
iris-mcp-blueprint = "iris_mcp_blueprint.entrypoint:main"
